---
# developer ssh homedir
- name: developer ssh homedir
  sudo: true
  file: path=/home/{{item.name}}/.ssh
        state=directory
        owner={{item.name}}
        group={{item.name}}
        mode=0750
  with_items: developers_all
  tags:
    - tsadm-site
    - developer-setup

# developer ssh config
- name: developer ssh config
  sudo: true
  template: src=developer-ssh-config
            dest=/home/{{item.name}}/.ssh/config
            owner={{item.name}}
            group={{item.name}}
            mode=0640
            backup=yes
  with_items:
    developers_all
  tags:
    - tsadm-site
    - developer-setup
