---
# developers homedir
- name: developers homedir
  sudo: true
  file: path={{tsadm_homedir}}/developer
    state=directory
    mode=0755
  tags:
    - developer-setup


# developer user
- name: developer user
  sudo: true
  user: name={{tsadmdb_user[item].slug}}
    comment='{{tsadm_user}} developer {{tsadmdb_user[item].name}}'
    shell=/bin/bash
    home={{tsadm_homedir}}/developer/{{tsadmdb_user[item].name}}
    state=present
    move_home=yes
  with_items:
    tsadm_developers
  when:
    - tsadmdb_user[item].setenv_devel == "1"
  tags:
    - developer-setup


# developer home perms
- name: developer home perms
  sudo: true
  file: path={{tsadm_homedir}}/developer/{{tsadmdb_user[item].name}}
    state=directory
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0750
  with_items:
    tsadm_developers
  when:
    - tsadmdb_user[item].setenv_devel == "1"
  tags:
    - developer-setup
