---
# developer user
- name: developer user
  sudo: true
  user: name={{item.name}}
        comment='tsadm developer {{item.name}}'
        shell=/bin/bash
        home=/home/{{item.name}}
        state=present
  with_items:
    developers_all
  tags:
    - developer-setup

# developer home perms
- name: developer home perms
  sudo: true
  file: path=/home/{{item.name}}
        state=directory
        owner={{item.name}}
        group={{item.name}}
        mode=0750
  with_items:
    developers_all
  tags:
    - developer-setup
