---
# developer ssh homedir
- name: developer ssh homedir
  sudo: true
  file: path=/home/{{tsadmdb_user[item].slug}}/.ssh
    state=directory
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0750
  with_items:
    tsadm_developers
  tags:
    - tsadm-site
    - developer-setup


# developer ssh config
- name: developer ssh config
  sudo: true
  template: dest=/home/{{tsadmdb_user[item].slug}}/.ssh/config
    src=developer-ssh-config
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0640
    backup=yes
  with_items:
    tsadm_developers
  tags:
    - tsadm-site
    - developer-setup


# developer ssh authorized_keys
- name: developer ssh authorized_keys
  sudo: true
  template: dest=/home/{{tsadmdb_user[item].slug}}/.ssh/authorized_keys
    src=developer-ssh-authorized_keys
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0600
    backup=yes
  with_items:
    tsadm_developers
  when:
    - item in tsadmdb_user_auth_keys
  tags:
    - tsadm-site
    - developer-setup
