---
# developer user
- name: developer user
  sudo: true
  user: name={{tsadm_developers[item].name}}
        comment='tsadm developer'
        shell=/bin/bash
        home=/home/{{tsadm_developers[item].name}}
        state=present
  with_items:
    tsadm_auth_developers
  tags:
    - developer-setup


# developer home perms
- name: developer home perms
  sudo: true
  file: path=/home/{{tsadm_developers[item].name}}
        state=directory
        owner={{tsadm_developers[item].name}}
        group={{tsadm_developers[item].name}}
        mode=0750
  with_items:
    tsadm_auth_developers
  tags:
    - developer-setup
