---
# developer user
- name: developer user
  sudo: true
  user: name={{tsadmdb_user[item].name}}
        comment='tsadm developer'
        shell=/bin/bash
        home=/home/{{tsadmdb_user[item].name}}
        state=present
  with_items:
    tsadm_developers
  tags:
    - developer-setup


# developer home perms
- name: developer home perms
  sudo: true
  file: path=/home/{{tsadmdb_user[item].name}}
        state=directory
        owner={{tsadmdb_user[item].name}}
        group={{tsadmdb_user[item].name}}
        mode=0750
  with_items:
    tsadm_developers
  tags:
    - developer-setup
