---
# developer ssh homedir
- name: developer ssh homedir
  sudo: true
  file: path=/home/{{tsadmdb_user[item].name}}/.ssh
        state=directory
        owner={{tsadmdb_user[item].name}}
        group={{tsadmdb_user[item].name}}
        mode=0750
  with_items:
    tsadm_developers
  tags:
    - tsadm-site
    - developer-setup


# developer ssh config
- name: developer ssh config
  sudo: true
  template: src=developer-ssh-config
            dest=/home/{{tsadmdb_user[item].name}}/.ssh/config
            owner={{tsadmdb_user[item].name}}
            group={{tsadmdb_user[item].name}}
            mode=0640
            backup=yes
  with_items:
    tsadm_developers
  tags:
    - tsadm-site
    - developer-setup


# developer ssh authorized_keys
- name: developer ssh authorized_keys
  sudo: true
  template: src=developer-ssh-authorized_keys
    dest=/home/{{tsadmdb_user[item].name}}/.ssh/authorized_keys
    owner={{tsadmdb_user[item].name}}
    group={{tsadmdb_user[item].name}}
    mode=0600
    backup=yes
  with_items:
    tsadm_developers
  tags:
    - tsadm-site
    - developer-setup
