---
# developer user
- name: developer user
  sudo: true
  user: name={{tsadmdb_user[item].slug}}
    comment='{{tsadm_user}} developer {{tsadmdb_user[item].name}}'
    shell=/bin/bash
    home=/home/{{tsadmdb_user[item].slug}}
    state=present
  with_items:
    tsadm_developers
  when:
    - tsadmdb_user[item].setenv_devel == 1
  tags:
    - developer-setup


# developer home perms
- name: developer home perms
  sudo: true
  file: path=/home/{{tsadmdb_user[item].slug}}
    state=directory
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0750
  with_items:
    tsadm_developers
  when:
    - tsadmdb_user[item].setenv_devel == 1
  tags:
    - developer-setup
