---
# tsadm drushrc dir
- name: tsadm drushrc dir
  file: path={{tsadm_homedir}}/.drush
        state=directory
  tags:
    - tsadm-site
    - site-drush


# site drush aliases
- name: site drush aliases
  template:
    src=site.aliases.drushrc.php
    dest={{tsadm_homedir}}/.drush/{{tsadmdb_site[item].name}}.aliases.drushrc.php
    mode=0640
    validate='php -l %s'
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site
    - site-drush


# site develoloer drush homedir
- name: site developer drush homedir
  sudo: true
  file:
    path=/home/{{tsadmdb_user[item].slug}}/.drush
    state=directory
    owner={{tsadmdb_user[item].slug}}
    group={{tsadmdb_user[item].slug}}
    mode=0750
  with_items:
    tsadm_developers
  when:
    - tsadmdb_user[item].setenv_devel == 1
  tags:
    - tsadm-site
    - site-drush


# site drush aliases for developer
- name: site drush aliases for developer
  sudo: true
  template:
    src=developer-site.aliases.drushrc.php
    dest=/home/{{tsadmdb_user[item.1].slug}}/.drush/{{tsadmdb_site[item.0.site_id].name}}.aliases.drushrc.php
    owner={{tsadmdb_user[item.1].slug}}
    group={{tsadmdb_user[item.1].slug}}
    mode=0640
    validate='php -l %s'
  with_subelements:
    - tsadm_site_auth
    - auth_users
  when:
    - tsadmdb_user[item.1].setenv_devel == 1
  tags:
    - tsadm-site
    - site-drush
