---
# tsadm drushrc dir
- name: tsadm drushrc dir
  sudo: true
  file: path={{tsadm_homedir}}/drushrc
        state=directory
  tags:
    - tsadm-site
    - site-drush

# site drush aliases
- name: site drush aliases
  sudo: true
  template: src=site.aliases.drushrc.php
            dest={{tsadm_homedir}}/drushrc/{{item.site_name}}.aliases.drushrc.php
            validate='php -l %s'
  with_items: sites_envs_all
  tags:
    - tsadm-site
    - site-drush

# site develoloer drush homedir
- name: site developer drush homedir
  sudo: true
  file: path=/home/{{item.name}}/.drush
        state=directory
  with_items: developers_all
  tags:
    - tsadm-site
    - site-drush

# site drush aliases for developer
- name: site drush aliases for developer
  sudo: true
  file: src={{tsadm_homedir}}/drushrc/{{item.1.name}}.aliases.drushrc.php
        path=/home/{{item.0.name}}/.drush/{{item.1.name}}.aliases.drushrc.php
        state=link
  with_subelements:
    - developers_all
    - sites_auth
  tags:
    - tsadm-site
    - site-drush
