---
# install debian packages
- include: ../../common/tasks/debian-packages.yml debian_packages_install={{master_pkg_install}}

- include: developer-os-user.yml
- include: developer-ssh-config.yml
- include: site-repo.yml
- include: site-repo-auth.yml
- include: drush-aliases.yml
