---
# repo ssh dir
- name: site repo ssh dir
  sudo: true
  file:
    path={{site_repo_basedir}}/{{tsadm_sites[item].name}}/.ssh
    state=directory
    owner={{tsadm_sites[item].name}}
    group={{tsadm_sites[item].name}}
    mode=0750
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site
    - site-repo
    - site-auth

# ssh auth
- name: site repo ssh auth
  sudo: true
  lineinfile: "dest={{site_repo_basedir}}/{{item.0.name}}/.ssh/authorized_keys state=present line='{{item.1}}' mode=0640 owner={{item.0.name}} group={{item.0.name}} create=yes"
  with_subelements:
    - sites_all_auth
    - auth_keys
  tags:
    - tsadm-site
    - site-repo
    - site-auth
