---
# repos basedir
- name: site repo basedir
  sudo: true
  file:
    path={{site_repo_basedir}}
    state=directory
    mode=0751
  tags:
    - tsadm-site
    - site-repo

# repo user
- name: site repo user
  sudo: true
  user:
    uid={{item}}
    name={{tsadm_sites[item].name}}
    groups={{repo_user_groups}}
    comment='tsadm repo {{tsadm_sites[item].name}}'
    home={{site_repo_basedir}}/{{tsadm_sites[item].name}}
    shell=/usr/bin/git-shell
    state=present
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site

# repo home perms
- name: site repo home perms
  sudo: true
  file:
    path={{site_repo_basedir}}/{{tsadm_sites[item].name}}
    state=directory
    owner={{tsadm_sites[item].name}}
    group={{tsadm_sites[item].name}}
    mode=0751
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site
    - site-repo

# git repo
- name: site git repo
  sudo: true
  script: git-repo-create.sh {{tsadm_sites[item].name}} {{site_repo_basedir}}/{{tsadm_sites[item].name}}/{{tsadm_sites[item].name}}.git {{www_group}} creates={{site_repo_basedir}}/{{tsadm_sites[item].name}}/{{tsadm_sites[item].name}}.git/description
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site
    - site-repo

# git post-receive hook
- name: site repo post-receive hook
  sudo: true
  file: src={{site_repo_post_receive_hook}}
        path={{site_repo_basedir}}/{{tsadm_sites[item].name}}/{{tsadm_sites[item].name}}.git/hooks/post-receive
        state=link
        force=yes
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site
    - site-repo
