---
# repos basedir
- name: site repo basedir
  sudo: true
  file:
    path={{site_repo_basedir}}
    state=directory
    mode=0751
  tags:
    - tsadm-site
    - site-repo


# repo user groups
- name: site repo user group
  sudo: true
  group:
    name={{repo_user_groups}}
    state=present


# repo user
- name: site repo user
  sudo: true
  user:
    name={{tsadmdb_site[item].slug}}
    groups={{repo_user_groups}}
    comment='{{tsadm_user}} {{tsadmdb_site[item].name}} repo'
    home={{site_repo_basedir}}/{{tsadmdb_site[item].name}}
    shell=/usr/bin/git-shell
    state=present
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site


# repo home perms
- name: site repo home perms
  sudo: true
  file:
    path={{site_repo_basedir}}/{{tsadmdb_site[item].name}}
    state=directory
    owner={{tsadmdb_site[item].slug}}
    group={{tsadmdb_site[item].slug}}
    mode=0751
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site
    - site-repo


# create git repo
- name: site create git repo
  sudo: true
  script: git-repo-create.sh {{tsadmdb_site[item].slug}} {{site_repo_basedir}}/{{tsadmdb_site[item].name}}/{{tsadmdb_site[item].name}}.git {{www_group}} creates={{site_repo_basedir}}/{{tsadmdb_site[item].name}}/{{tsadmdb_site[item].name}}.git/description
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site
    - site-repo


# git post-receive hook
- name: site repo post-receive hook
  sudo: true
  file:
    src={{site_repo_post_receive_hook}}
    path={{site_repo_basedir}}/{{tsadmdb_site[item].name}}/{{tsadmdb_site[item].name}}.git/hooks/post-receive
    state=link
    force=yes
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site
    - site-repo
