---
# repos basedir
- name: site repo basedir
  sudo: true
  file:
    path={{site_repo_basedir}}
    state=directory
    owner=root
    group=root
    mode=0751
  tags:
    - tsadm-site
    - site-repo

# repo user
- name: site repo user
  sudo: true
  user:
    uid={{item.uid}}
    name={{item.name}}
    groups={{repo_user_groups}}
    comment='tsadm repo {{item.name}}'
    home={{site_repo_basedir}}/{{item.name}}
    shell=/usr/bin/git-shell
    state=present
  with_items:
    sites_all
  tags: tsadm-site

# repo home perms
- name: site repo home perms
  sudo: true
  file:
    path={{site_repo_basedir}}/{{item.name}}
    state=directory
    owner={{item.name}}
    group={{item.name}}
    mode=0751
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo

# git repo
- name: site git repo
  sudo: true
  script: git-repo-create.sh {{item.name}} {{site_repo_basedir}}/{{item.name}}/{{item.name}}.git {{www_group}} creates={{site_repo_basedir}}/{{item.name}}/{{item.name}}.git/description
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo

# repo ssh dir
- name: site repo ssh dir
  sudo: true
  file:
    path={{site_repo_basedir}}/{{item.name}}/.ssh
    state=directory
    owner={{item.name}}
    group={{item.name}}
    mode=0750
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo
    - repo-ssh-auth

# ssh auth
- name: site repo ssh auth
  sudo: true
  lineinfile: "dest={{site_repo_basedir}}/{{item.0.name}}/.ssh/authorized_keys state=present line='{{item.1}}' mode=0640 owner={{item.0.name}} group={{item.0.name}} create=yes"
  with_subelements:
    - sites_all
    - auth_keys
  tags:
    - tsadm-site
    - site-repo
    - repo-ssh-auth
