---
# repo ssh dir
- name: site repo ssh dir
  sudo: true
  file:
    path={{site_repo_basedir}}/{{tsadm_sites[item].name}}/.ssh
    state=directory
    owner={{tsadm_sites[item].name}}
    group={{tsadm_sites[item].name}}
    mode=0750
  with_items:
    tsadm_sites_repo
  tags:
    - tsadm-site
    - site-repo
    - site-auth


# ssh auth
- name: site repo ssh auth
  sudo: true
  template: src=site-repo-ssh-authorized_keys
    dest={{site_repo_basedir}}/{{tsadm_sites[item.id].name}}/.ssh/authorized_keys
    owner={{tsadm_sites[item.id].name}}
    group={{tsadm_sites[item.id].name}}
    mode=0600
    backup=yes
  with_items:
    tsadm_sites_repo_auth
  tags:
    - tsadm-site
    - site-repo
    - site-auth
