---
# repos basedir
- name: site repo basedir
  sudo: true
  file:
    path={{site_repo_basedir}}
    state=directory
    mode=0751
  tags:
    - tsadm-site
    - site-repo

# repo user
- name: site repo user
  sudo: true
  user:
    uid={{item.uid}}
    name={{item.name}}
    groups={{repo_user_groups}}
    comment='tsadm repo {{item.name}}'
    home={{site_repo_basedir}}/{{item.name}}
    shell=/usr/bin/git-shell
    state=present
  with_items:
    sites_all
  tags: tsadm-site

# repo home perms
- name: site repo home perms
  sudo: true
  file:
    path={{site_repo_basedir}}/{{item.name}}
    state=directory
    owner={{item.name}}
    group={{item.name}}
    mode=0751
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo

# git repo
- name: site git repo
  sudo: true
  script: git-repo-create.sh {{item.name}} {{site_repo_basedir}}/{{item.name}}/{{item.name}}.git {{www_group}} creates={{site_repo_basedir}}/{{item.name}}/{{item.name}}.git/description
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo

# git post-receive hook
- name: site repo post-receive hook
  sudo: true
  file: src={{site_repo_post_receive_hook}}
        path={{site_repo_basedir}}/{{item.name}}/{{item.name}}.git/hooks/post-receive
        state=link
        force=yes
  with_items: sites_all
  tags:
    - tsadm-site
    - site-repo
