---
# repo ssh dir
- name: site repo ssh dir
  sudo: true
  file:
    path={{site_repo_basedir}}/{{tsadmdb_site[item].name}}/.ssh
    state=directory
    owner={{tsadmdb_site[item].name}}
    group={{tsadmdb_site[item].name}}
    mode=0750
  with_items:
    tsadmdb_site.keys()
  tags:
    - tsadm-site
    - site-repo
    - site-auth


# ssh auth
- name: site repo ssh auth
  sudo: true
  template: src=site-repo-ssh-authorized_keys
    dest={{site_repo_basedir}}/{{tsadmdb_site[item].name}}/.ssh/authorized_keys
    owner={{tsadmdb_site[item].name}}
    group={{tsadmdb_site[item].name}}
    mode=0600
    backup=yes
  with_items:
    tsadm_site_auth.keys()
  tags:
    - tsadm-site
    - site-repo
    - site-auth
