# certs dir group and permissions
- name: ssl certs dir
  sudo: true
  file: path={{tsadm_etcdir}}/ssl
    group={{tsadm_certs_group}}
    mode=0750
    state=directory


# gitbot cert file perms
- name: webapp gitbot cert
  sudo: true
  file: path={{tsadm_etcdir}}/ssl/gitbot.pem
    group={{tsadm_certs_group}}
    mode=0640
    state=file
