---
# get all servers facts
- hosts: all
  gather_facts: false
  tasks:
    - name: tsadm facts
      sudo: true
      action: tsadm_facts
      tags:
        - tsadm-site
        - env-vhost


# master server
- hosts: master_server
  gather_facts: false
  roles:
    - common
    - master-server


# slave servers
- hosts: slave_servers
  gather_facts: false
  roles:
    - common
    - slave-server
