---
# git repo
- hosts: master-server
  gather_facts: false
  tasks:
    - include: roles/master-server/tasks/site-repo.yml

# site installation
- hosts: slave-servers
  gather_facts: false
  tasks:
    - include: roles/slave-server/tasks/site-user.yml
