---
- name: tsadm codebase dir perms
  sudo: true
  file:
    path={{tsadm_basedir}}
    state=directory
    owner={{tsadm_user}}
    group={{tsadm_group}}
  tags:
    - tsadm-codebase


- name: tsadm codebase sync config
  synchronize:
    src={{tsadm_webapp_codebase}}/tsadm/config.py
    dest={{tsadm_basedir}}/tsadm/
    archive=yes
    delete=no
  notify:
    - tsadm codebase compile
  tags:
    - tsadm-codebase


- name: tsadm codebase sync log module
  synchronize:
    src={{tsadm_webapp_codebase}}/tsadm/log.py
    dest={{tsadm_basedir}}/tsadm/
    archive=yes
    delete=no
  notify:
    - tsadm codebase compile
  tags:
    - tsadm-codebase


- name: tsadm codebase modules dir perms
  file:
    path={{tsadm_basedir}}/tsadm
    state=directory
    owner={{tsadm_user}}
    group={{tsadm_group}}
  tags:
    - tsadm-codebase


- name: tsadm codebase sync libexec
  synchronize:
    src={{tsadm_webapp_codebase}}/libexec/
    dest={{tsadm_basedir}}/libexec/
    archive=yes
    delete=no
  notify:
    - tsadm codebase compile
  tags:
    - tsadm-codebase


- name: tsadm codebase etcdir perms
  sudo: true
  file:
    path={{tsadm_etcdir}}
    state=directory
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0751
  tags:
    - tsadm-codebase


- name: tsadm codebase sync etcdir
  synchronize:
    src={{tsadm_webapp_codebase}}/etc/
    dest={{tsadm_etcdir}}/
    archive=yes
    delete=no
    perms=no
  notify:
    - service xinetd restart
  tags:
    - tsadm-codebase


- name: tsadm webapp config.json
  template: src=webapp-config.json
    dest={{tsadm_etcdir}}/config.json
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0440
  tags:
    - tsadm-codebase


- name: tsadm webapp config.json README
  template: src=webapp-config.json.README
    dest={{tsadm_etcdir}}/config.json.README
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0440
  tags:
    - tsadm-codebase
