---
# tsadm drupal.settings.php
- name: tsadm drupal.settings.php
  sudo: true
  template: dest={{tsadm_homedir}}/
    src=drupal.settings.php
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    mode=0440
    validate='php -l %s'
  tags:
    - tsadm-site
    - site-envs


# tsadm drupal settings dir
- name: tsadm drupal settings dir
  sudo: true
  file: path={{tsadm_homedir}}/drupal-settings
    state=directory
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    mode=0510
  tags:
    - tsadm-site
    - site-envs


# siteenv drupal db settings
- name: siteenv drupal db settings
  sudo: true
  template: dest={{tsadm_homedir}}/drupal-settings/{{tsadmdb_siteenv[item].site_name}}.{{tsadmdb_siteenv[item].name}}-db.php
    src=siteenv-drupal-settings-db.php
    mode=0440
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    validate='php -l %s'
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-envs


# tsadm drupal private dir
- name: tsadm drupal private dir
  sudo: true
  file: path={{tsadm_homedir}}/private
    state=directory
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    mode=0510
  tags:
    - tsadm-site
    - site-envs


# siteenv drupal private dir
- name: siteenv drupal private dir
  sudo: true
  file: path={{tsadm_homedir}}/private/{{tsadmdb_siteenv[item].site_name}}.{{tsadmdb_siteenv[item].name}}
    state=directory
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    mode=2770
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-envs


# siteenv drupal temp dir
- name: siteenv drupal temp dir
  sudo: true
  file: path={{tsadm_homedir}}/private/{{tsadmdb_siteenv[item].site_name}}.{{tsadmdb_siteenv[item].name}}/tmp
    state=directory
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    mode=2770
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-envs
