---
# drush bin install
- name: drush bin install
  sudo: true
  get_url:
    dest=/usr/local/bin/drush8
    force=no
    mode=0755
    url=https://github.com/drush-ops/drush/releases/download/8.0.5/drush.phar
    sha256sum=f6fc333036d8993bd2a834c277e262d200c3075e82c869c213c62ce331f86b77
  tags:
    - tsadm-site
    - site-drush


# drush bin symlink
- name: drush bin symlink
  sudo: true
  file:
    dest=/usr/local/bin/drush
    src=/usr/local/bin/drush8
    state=link
  tags:
    - tsadm-site
    - site-drush
