---
# site drush dir
- name: site drush dir
  sudo: true
  file:
    path={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}/.drush
    state=directory
    mode=0750
    owner={{tsadmdb_site[item].name}}
    group={{www_group}}
  with_items:
    tsadm_slave_sites
  tags:
    - tsadm-site
    - site-drush


# site drush aliases
- name: site drush aliases
  sudo: true
  template:
    src=site.aliases.drushrc.php
    dest={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}/.drush/{{tsadmdb_site[item].name}}.aliases.drushrc.php
    mode=0640
    owner={{tsadmdb_site[item].name}}
    group={{www_group}}
    validate='php -l %s'
    backup=yes
  with_items:
    tsadm_slave_sites
  tags:
    - tsadm-site
    - site-drush


# tsadm user drush dir
- name: tsadm user drush dir
  file:
    path={{tsadm_homedir}}/.drush
    state=directory
    mode=0750
    owner={{tsadm_user}}
    group={{tsadm_group}}
  tags:
    - tsadm-site
    - site-drush


# tsadm user drush aliases
- name: tsadm user drush aliases
  template:
    src=site.aliases.drushrc.php
    dest={{tsadm_homedir}}/.drush/{{tsadmdb_site[item].name}}.aliases.drushrc.php
    mode=0640
    owner={{tsadm_user}}
    group={{tsadm_group}}
    validate='php -l %s'
    backup=yes
  with_items:
    tsadm_slave_sites
  tags:
    - tsadm-site
    - site-drush
