---
# install debian packages
- include: ../../common/tasks/debian-packages.yml debian_packages_install={{slave_pkg_install}}

- include: codebase-sync.yml
- include: xinetd-jobq.yml
- include: site-user.yml
- include: site-auth.yml
- include: site-envs.yml
- include: drush-aliases.yml
- include: site-env-database.yml
- include: site-env-vhost.yml
- include: drupal-setup.yml
