---
# site env database
- name: site env db
  mysql_db:
    name={{item.0.site_name}}{{item.1.name}}db
    state=present
  with_subelements:
    - sites_envs_all
    - envs
  tags:
    - tsadm-site
    - site-env-db


# site env database user
- name: site env db user
  mysql_user:
    name={{item.0.site_name}}
    password="{{ lookup('password', inventory_hostname + '.' + item.0.site_name + '.my.passwd chars=ascii_letters,digits') }}"
    priv={{item.0.site_name}}%db.*:ALL
    state=present
  with_subelements:
    - sites_envs_all
    - envs
  tags:
    - tsadm-site
    - site-env-db


# site env database access file
- name: site env db access file
  sudo: true
  template:
    src=site.my.cnf
    dest={{tsadm_homedir}}/sites/{{item.site_name}}/.my.cnf
    mode=0640
    owner={{tsadm_user}}
    group={{www_group}}
  with_items:
    sites_envs_all
  tags:
    - tsadm-site
    - site-env-db
