---
# robots disallow file
- name: robots disallow file
  sudo: true
  copy: dest={{hostvars[inventory_hostname].tsadm_apache_runcfg.docroot}}/
    src=robots-disallow.txt
    mode=0644
  tags:
    - env-vhost


# robots disallow readme
- name: robots disallow readme
  sudo: true
  copy: dest={{hostvars[inventory_hostname].tsadm_apache_runcfg.docroot}}/
    src=robots-disallow.txt.README
    mode=0400
  tags:
    - env-vhost


# drupal common live vhost
- name: drupal common live vhost
  template: dest={{tsadm_etcdir}}/apache/drupal-live-vhost.conf
    src=drupal-live-vhost.conf
    mode=0640
  notify:
    - service apache2 restart
  tags:
    - env-vhost


# drupal common non-live vhost
- name: drupal common non-live vhost
  template: dest={{tsadm_etcdir}}/apache/drupal-vhost.conf
    src=drupal-vhost.conf
    mode=0640
  notify:
    - service apache2 restart
  tags:
    - env-vhost


# env vhost file
- name: site env vhost file
  sudo: true
  template: dest=/etc/apache2/sites-enabled/{{tsadmdb_siteenv[item].site_id}}-{{tsadmdb_siteenv[item].site_slug}}{{tsadmdb_siteenv[item].name}}.conf
    src=site-env-apache.conf
    mode=0640
  with_items:
    tsadm_slave_siteenvs
  notify:
    - service apache2 restart
  tags:
    - env-vhost
