---
# site ssh dir
- name: site ssh dir
  sudo: true
  file:
    path={{tsadm_homedir}}/sites/{{item.name}}/.ssh
    state=directory
    owner={{item.name}}
    group={{www_group}}
    mode=0750
  with_items:
    slave_sites
  tags:
    - tsadm-site
    - site-repo
    - site-auth


# site ssh auth
- name: site ssh auth
  sudo: true
  lineinfile:
    dest={{tsadm_homedir}}/sites/{{item.0.name}}/.ssh/authorized_keys
    state=present
    line='{{item.1}}'
    mode=0640
    owner={{item.0.name}}
    group={{www_group}}
    create=yes
  with_subelements:
    - slave_sites_auth
    - auth_keys
  tags:
    - tsadm-site
    - site-repo
    - site-auth
