---
# apache.d auto-config files dir
- name: apache.d auto-configs dir
  sudo: true
  file: dest={{tsadm_etcdir}}/apache.d
    mode=0751
    state=directory
  tags:
    - env-vhost


# apache.d README file
- name: apache.d README
  sudo: true
  copy: dest={{tsadm_etcdir}}/apache.d/
    src=apache.d-README
    mode=0400
  tags:
    - env-vhost


# robots disallow file
- name: robots disallow file
  sudo: true
  copy: dest={{tsadm_etcdir}}/apache.d/
    src=robots-disallow.txt
    mode=0440
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
  tags:
    - env-vhost


# drupal common live vhost
- name: drupal common live vhost
  sudo: true
  template: dest={{tsadm_etcdir}}/apache.d/drupal-live-vhost.inc
    src=drupal-live-vhost.conf
    mode=0440
  notify:
    - service apache2 restart
  tags:
    - env-vhost


# drupal common non-live vhost
- name: drupal common non-live vhost
  sudo: true
  template: dest={{tsadm_etcdir}}/apache.d/drupal-vhost.inc
    src=drupal-vhost.conf
    mode=0440
  notify:
    - service apache2 restart
  tags:
    - env-vhost


# env vhost file
- name: site env vhost file
  sudo: true
  template: dest={{tsadm_etcdir}}/apache.d/{{tsadmdb_siteenv[item].site_id}}-{{tsadmdb_siteenv[item].site_slug}}{{tsadmdb_siteenv[item].name}}.conf
    src=site-env-apache.conf
    mode=0440
  with_items:
    tsadm_slave_siteenvs
  notify:
    - service apache2 restart
  tags:
    - env-vhost
