---
# site env database
- name: site env db
  mysql_db:
    name={{tsadmdb_siteenv[item].site_name}}{{tsadmdb_siteenv[item].name}}db
    state=present
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db


# site env database user
- name: site env db user
  mysql_user:
    name={{tsadmdb_siteenv[item].site_name}}
    password="{{ lookup('password', inventory_hostname + '.' + tsadmdb_siteenv[item].site_name + '.my.passwd chars=ascii_letters,digits') }}"
    priv={{tsadmdb_siteenv[item].site_name}}%db.*:ALL
    state=present
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db


# site env database access file
- name: site env db access file
  sudo: true
  template:
    src=site.my.cnf
    dest={{tsadm_homedir}}/sites/{{tsadmdb_siteenv[item].site_name}}/.my.cnf
    mode=0640
    owner={{tsadm_user}}
    group={{www_group}}
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db
