---
# site env database
- name: site env db
  mysql_db:
    name={{tsadmdb_siteenv[item].site_slug}}{{tsadmdb_siteenv[item].name}}db
    login_host={{mysql_login_host}}
    state=present
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db


# site env database user
- name: site env db user
  mysql_user:
    name={{tsadmdb_siteenv[item].site_slug}}
    login_host={{mysql_login_host}}
    password="{{ lookup('password', privdir+'/'+inventory_hostname+'.'+tsadmdb_siteenv[item].site_slug+'.my.passwd chars=ascii_letters,digits') }}"
    priv={{tsadmdb_siteenv[item].site_slug}}%db.*:ALL
    state=present
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db


# site env database access file
- name: site env db access file
  sudo: true
  template:
    src=site.my.cnf
    dest={{tsadm_homedir}}/sites/{{tsadmdb_siteenv[item].site_name}}/.my.cnf
    mode=0640
    owner={{tsadmdb_siteenv[item].site_slug}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
  with_items:
    tsadm_slave_siteenvs
  tags:
    - tsadm-site
    - site-env-db
