---
# site ssh dir
- name: site ssh dir
  sudo: true
  file:
    path={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}/.ssh
    state=directory
    owner={{tsadmdb_site[item].name}}
    group={{www_group}}
    mode=0750
  with_items:
    tsadm_slave_sites
  tags:
    - tsadm-site
    - site-repo
    - site-auth


# ssh auth
- name: site ssh auth
  sudo: true
  template:
    src=site-ssh-authorized_keys
    dest={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}/.ssh/authorized_keys
    owner={{tsadmdb_site[item].name}}
    group={{www_group}}
    mode=0600
    backup=yes
  with_items:
    tsadm_slave_sites
  tags:
    - tsadm-site
    - site-repo
    - site-auth
