---
# git checkout
- name: site env git checkout
  sudo: true
  git:
    dest={{tsadm_homedir}}/sites/{{tsadmdb_siteenv[item].site_name}}/{{tsadmdb_siteenv[item].name}}
    repo={{tsadmdb_siteenv[item].site_repo_uri}}
    key_file={{tsadm_homedir}}/.ssh/id_rsa
    accept_hostkey=yes
    force=no
  with_items:
    tsadm_slave_siteenvs
  when:
    site_repo_git_checkout and (tsadmdb_siteenv[item].site_parent_id == "0")
  tags:
    - tsadm-site
    - site-envs


# create link to parent site's env
- name: site env parent symlink
  sudo: true
  file: path={{tsadm_homedir}}/sites/{{tsadmdb_siteenv[item].site_name}}/{{tsadmdb_siteenv[item].name}}
    src={{tsadm_homedir}}/sites/{{tsadmdb_site[tsadmdb_siteenv[item].site_parent_id].name}}/{{tsadmdb_siteenv[item].name}}
    state=link
    force=yes
  with_items:
    tsadm_slave_siteenvs
  when:
    tsadmdb_siteenv[item].site_parent_id != "0"
  tags:
    - tsadm-site
    - site-envs


# env files/dirs permissions
- name: site env perms
  sudo: true
  site_env_perms:
    env_basedir={{tsadm_homedir}}/sites/{{tsadmdb_siteenv[item].site_name}}/{{tsadmdb_siteenv[item].name}}
    owner={{tsadm_user}}
    group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    public_owner={{tsadmdb_siteenv[item].site_slug}}
    public_group={{hostvars[inventory_hostname].tsadm_apache_runcfg.group.name}}
    public_dir_mode=2770
    public_file_mode=0660
    public_path_regex=r'.*/sites/.*/files($|/.*)'
  with_items:
    tsadm_slave_siteenvs
  when:
    site_perms_check and (tsadmdb_siteenv[item].site_parent_id == "0")
  tags:
    - tsadm-site
    - site-envs
    - site-env-perms
