---
# sites homedir base
- name: site homedir base
  sudo: true
  file:
    path={{tsadm_homedir}}/sites
    state=directory
    owner={{tsadm_user}}
    group={{www_group}}
    mode=0751
  tags:
    tsadm-site


# site user
- name: site user
  sudo: true
  user:
    name={{tsadmdb_site[item].slug}}
    comment='{{tsadm_user}} {{tsadmdb_site[item].name}} site'
    group={{www_group}}
    home={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}
    shell=/bin/bash
    state=present
  with_items:
    tsadm_slave_sites
  tags:
    tsadm-site


# site user homedir data
- name: site user homedir data
  sudo: true
  copy:
    src=site-user.home/
    dest={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}
    owner={{tsadmdb_site[item].slug}}
    group={{www_group}}
    backup=yes
    force=yes
  with_items:
    tsadm_slave_sites
  tags: tsadm-site


# site user home dir perms
- name: site user homedir perms
  sudo: true
  file:
    path={{tsadm_homedir}}/sites/{{tsadmdb_site[item].name}}
    state=directory
    owner={{tsadmdb_site[item].slug}}
    group={{www_group}}
    mode=0751
  with_items:
    tsadm_slave_sites
  tags: tsadm-site
