---
- name: xinetd jobq config
  file:
    path={{xinetd_jobqd_conf}}
    force=yes
    src={{tsadm_etcdir}}/xinetd/jobqd.conf
    state=link
  notify:
    - service xinetd restart
  tags:
    - tsadm-codebase
