---
# tsadm user group
- name: tsadm user group
  group: name={{tsadm_group}} state=present
  tags:
    - tsadm-user


# tsadm user
- name: tsadm user
  user:
    name={{tsadm_user}}
    comment=tsadm
    group={{tsadm_group}}
    home={{tsadm_homedir}}
    shell=/bin/bash
    state=present
  tags:
    - tsadm-user


# tsadm user homedir data
- name: tsadm homedir data
  copy:
    src=tsadm.home/
    dest={{tsadm_homedir}}
    mode=0640
    owner={{tsadm_user}}
    group={{tsadm_group}}
    backup=yes
    force=yes
  tags:
    - tsadm-user


# tsadm user homedir perms
- name: tsadm homedir perms
  file:
    path={{tsadm_homedir}}
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0750
    state=directory
  tags:
    - tsadm-user


# tsadm user ssh dir
- name: tsadm user ssh dir
  file:
    path={{tsadm_homedir}}/.ssh
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0750
    state=directory
  tags:
    - tsadm-user


# tsadm user ssh keygen
- name: tsadm user ssh keygen
  command:
    /usr/bin/ssh-keygen -q -t rsa -f {{tsadm_homedir}}/.ssh/id_rsa -N '' -C 'tsadm@{{inventory_hostname}}'
    creates={{tsadm_homedir}}/.ssh/id_rsa
  tags:
    - tsadm-user


# tsadm user ssh priv key perms
- name: tsadm user ssh priv key perms
  file:
    path={{tsadm_homedir}}/.ssh/id_rsa
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0640
    state=file
  tags:
    - tsadm-user


# tsadm user ssh pub key perms
- name: tsadm user ssh pub key perms
  file:
    path={{tsadm_homedir}}/.ssh/id_rsa.pub
    owner={{tsadm_user}}
    group={{tsadm_group}}
    mode=0640
    state=file
  tags:
    - tsadm-user
